### ISSUE TITLE
Yes/no input method is not clear on questions asked during installation

### ISSUE THREAD

**Issue by jackfirth** [racket/xrepl#1]
When I executed the ,install! command, I got this output:

```
-> ,install!
; writing new contents, with an added "(require xrepl)"
; (if you want to load it conditionally, edit the file and
;  use "(dynamic-require 'xrepl #f)" instead, which is a plain expression)
; OK to continue?
```

At the question prompt, I didn't know what to write. After brief experimentation, figured out typing "yes" works. After studying the source, it *looks* like any string starting with Y or y works as true, anything else as false, but I can't be certain. This caused brief confusion

Would it be a good idea to add some sort of `(yes/no)` text there?

**Comment by jackfirth** [comment]
Thanks @stamourv!

**Comment by stamourv** [comment]
I made the fix a while back, and somehow forgot to push it. Seeing your email still sitting in my inbox reminded me. :)
