### ISSUE TITLE
xrepl won't accept unicode input

### ISSUE THREAD

**Issue by lotabout** [racket/xrepl#4]
1. follow the instruction to enable xrepl: https://docs.racket-lang.org/xrepl/
2. Try to input unicode characters into the racket REPL, such as the lambda symbol `λ`
   1. under Linux, nothing shows up.
   2. under Mac, REPL will treat it as `\U+XXX\U+XXX` (sorry I don't remember the code).
3. When I disable XREPL, it works well.

**Comment by mflatt** [comment]
See racket/racket#1956

(Thanks, very belatedly, for the report!)
