### ISSUE TITLE
what is "[,bt for context]"?

### ISSUE THREAD

**Issue by mbutterick** [racket/xrepl#6]
I see this in error messages sometimes and have traced it [to this module](https://github.com/racket/xrepl/blob/master/xrepl-lib/xrepl/xrepl.rkt#L1563), which calls it a “temporary hack”. It looks like something is meant to be spliced in — a backtrace, I’m supposing — and isn’t … ?

[See the mailing list](https://groups.google.com/forum/#!searchin/racket-users/%22bt$20for$20context%22%7Csort:date) for examples going back to 2012.

**Comment by samth** [comment]
It means use the `,bt` xrepl command to show the context of the error (in most cases, that means the backtrace -- thus "bt").

**Comment by mbutterick** [comment]
So you only see it if `xrepl` is loaded?
And it means `[type ,bt at the REPL to see error context]`?

**Comment by samth** [comment]
Yes, and yes.

**Comment by renatoathaydes** [comment]
Hi... I see this message in Dr. Racket, but typing `,bt` doesn't help even after typing `(require xrepl)`. How can I actually use this in Dr. Racket??

**Comment by rfindler** [comment]
In DrRacket, you don't need xrepl. Click on the stop icon that has three
stop signs in it.
